// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using atm_driver.Clases;

#nullable disable

namespace atm_driver.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250112154926_Name-Changed")]
    partial class NameChanged
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("atm_driver.Models.Cajeros_Model", b =>
                {
                    b.Property<int>("cajero_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cajero_id"));

                    b.Property<string>("clave_comunicacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("clave_masterKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("localizacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("cajero_id");

                    b.ToTable("Cajeros");
                });

            modelBuilder.Entity("atm_driver.Models.Sistemas_Comunicacion_Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DireccionIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Ebcdc")
                        .HasColumnType("bit");

                    b.Property<bool>("Empaquetado")
                        .HasColumnType("bit");

                    b.Property<string>("Encabezado")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("LongitudPaquete")
                        .HasColumnType("int");

                    b.Property<int>("PuertoSoapApi")
                        .HasColumnType("int");

                    b.Property<int>("PuertoTcp")
                        .HasColumnType("int");

                    b.Property<string>("ServidorSoapApi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SocketTcp")
                        .HasColumnType("int");

                    b.Property<int>("TipoConexion")
                        .HasColumnType("int");

                    b.Property<int>("TipoConexionTcp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sistemas_Comunicacion");
                });
#pragma warning restore 612, 618
        }
    }
}
